In [10]:
import numpy as np
import pandas as pd

In [11]:
class Particle:
   
    def __init__(self, dims, p_range, v_range):
        
        #dims = number of dimensions
        #p= position of the particle in the dimentional space
        #v = velocity of the particle in the dimensional space
        #p_range = range of dimensions 
        #v_range = range of velocities
        
        #let the position and velocity of a praticle be randomly selected from uniform distribution
        self.p = np.random.uniform(p_range[0], p_range[1], (dims, ))
        self.v = np.random.uniform(v_range[0], v_range[1], (dims, )) 
        
        #the best position for any particle can be positive infinity
        self.pbest = np.inf
        
        #define particles best position based on specified dimensions
        self.pbestpos = np.zeros((dims, ))

In [12]:
class Swarm:
    
    def __init__(self, particle_no, dims, p_range, v_range, alpha_range, component):
        
        #particle_no = number of particles
        #dims = dimensions
        #p_range = range of dimensions 
        #v_range = range of velocities
        #alpha_range = inertia weight range
        #components = cognetive and social components
        
        
        #define the swarm with praticles from Class Particle
        self.p = np.array([Particle(dims, p_range, v_range) for i in range(particle_no)])
        
        #define global best as infinity
        self.gbest = np.inf
        
        #define global best poition
        self.gbestpos = np.zeros((dims, ))
        
        self.p_range = p_range
        self.v_range = v_range
        
        self.alpha_range = alpha_range
        
        #components
        self.component0 = component[0]
        self.component1 = component[1]
        self.dims = dims
       
    def optimize(self, function, input_X, output_Y,  print_step,  iter):
  
        for i in range(iter):
            for particle in self.p:
                fitness = function(input_X, output_Y, particle.p)

                #select the particles best position
                if fitness.any() < particle.pbest:
                    particle.pbest = fitness.any()
                    particle.pbestpos = particle.p.copy()
                    
                #select the global best position    
                if fitness.any() < self.gbest:
                    self.gbest = fitness.any()
                    self.gbestpos = particle.p.copy()
                    

            for particle in self.p:
               
                alpha = np.random.uniform(self.alpha_range[0], self.alpha_range[1], 1)[0]
                
                #velocity update formula
                particle.v = alpha * particle.v + (self.component0 * np.random.uniform(0.0, 1.0, (self.dims, )) * \
                (particle.pbestpos - particle.p)) + (self.component1 * np.random.uniform(0.0, 1.0, (self.dims, )) \
                * (self.gbestpos - particle.p))
                epsilon = 1
                #particle.v = particle.v.clip(min=self.v_range[0], max=self.v_range[1])
                particle.p = particle.p + epsilon * particle.v
                #particle.x = particle.x.clip(min=self.x_range[0], max=self.x_range[1])
                    
            if i % print_step == 0:
                print('iteration#: ', i+1,  ' loss: ', fitness)

        print("global best loss: ", self.gbest)
        
    def get_best_solution(self):
    
        return self.gbestpos   


In [13]:
import csv
with open("X_linear.csv", 'r') as f:
    Xin = list(csv.reader(f, delimiter=";"))
import numpy as np
Xin = np.array(Xin[1:], dtype=np.float)
print(Xin)
print(Xin.shape)

[[-1.  ]
 [-0.98]
 [-0.96]
 [-0.94]
 [-0.92]
 [-0.9 ]
 [-0.88]
 [-0.86]
 [-0.84]
 [-0.82]
 [-0.8 ]
 [-0.78]
 [-0.76]
 [-0.74]
 [-0.72]
 [-0.7 ]
 [-0.68]
 [-0.66]
 [-0.64]
 [-0.62]
 [-0.6 ]
 [-0.58]
 [-0.56]
 [-0.54]
 [-0.52]
 [-0.5 ]
 [-0.48]
 [-0.46]
 [-0.44]
 [-0.42]
 [-0.4 ]
 [-0.38]
 [-0.36]
 [-0.34]
 [-0.32]
 [-0.3 ]
 [-0.28]
 [-0.26]
 [-0.24]
 [-0.22]
 [-0.2 ]
 [-0.18]
 [-0.16]
 [-0.14]
 [-0.12]
 [-0.1 ]
 [-0.08]
 [-0.06]
 [-0.04]
 [-0.02]
 [ 0.  ]
 [ 0.02]
 [ 0.04]
 [ 0.06]
 [ 0.08]
 [ 0.1 ]
 [ 0.12]
 [ 0.14]
 [ 0.16]
 [ 0.18]
 [ 0.2 ]
 [ 0.22]
 [ 0.24]
 [ 0.26]
 [ 0.28]
 [ 0.3 ]
 [ 0.32]
 [ 0.34]
 [ 0.36]
 [ 0.38]
 [ 0.4 ]
 [ 0.42]
 [ 0.44]
 [ 0.46]
 [ 0.48]
 [ 0.5 ]
 [ 0.52]
 [ 0.54]
 [ 0.56]
 [ 0.58]
 [ 0.6 ]
 [ 0.62]
 [ 0.64]
 [ 0.66]
 [ 0.68]
 [ 0.7 ]
 [ 0.72]
 [ 0.74]
 [ 0.76]
 [ 0.78]
 [ 0.8 ]
 [ 0.82]
 [ 0.84]
 [ 0.86]
 [ 0.88]
 [ 0.9 ]
 [ 0.92]
 [ 0.94]
 [ 0.96]
 [ 0.98]]
(100, 1)


In [14]:
#input_X = layer1_input.values
input_X= Xin
input_X

array([[-1.  ],
       [-0.98],
       [-0.96],
       [-0.94],
       [-0.92],
       [-0.9 ],
       [-0.88],
       [-0.86],
       [-0.84],
       [-0.82],
       [-0.8 ],
       [-0.78],
       [-0.76],
       [-0.74],
       [-0.72],
       [-0.7 ],
       [-0.68],
       [-0.66],
       [-0.64],
       [-0.62],
       [-0.6 ],
       [-0.58],
       [-0.56],
       [-0.54],
       [-0.52],
       [-0.5 ],
       [-0.48],
       [-0.46],
       [-0.44],
       [-0.42],
       [-0.4 ],
       [-0.38],
       [-0.36],
       [-0.34],
       [-0.32],
       [-0.3 ],
       [-0.28],
       [-0.26],
       [-0.24],
       [-0.22],
       [-0.2 ],
       [-0.18],
       [-0.16],
       [-0.14],
       [-0.12],
       [-0.1 ],
       [-0.08],
       [-0.06],
       [-0.04],
       [-0.02],
       [ 0.  ],
       [ 0.02],
       [ 0.04],
       [ 0.06],
       [ 0.08],
       [ 0.1 ],
       [ 0.12],
       [ 0.14],
       [ 0.16],
       [ 0.18],
       [ 0.2 ],
       [ 0.22],
       [

In [15]:
print(input_X.shape)

(100, 1)


In [16]:
output_Y = np.zeros(shape=(100,1))

In [17]:
perfect_predict_Y = np.full((100, 1), 1, dtype=int)

In [18]:
print(perfect_predict_Y.shape)
perfect_predict_Y 

(100, 1)


array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [19]:
def linear(input_X):
    output_Y = input_X * 1
    return output_Y

In [20]:
output_Y = linear(input_X)

In [21]:
output_Y

array([[-1.  ],
       [-0.98],
       [-0.96],
       [-0.94],
       [-0.92],
       [-0.9 ],
       [-0.88],
       [-0.86],
       [-0.84],
       [-0.82],
       [-0.8 ],
       [-0.78],
       [-0.76],
       [-0.74],
       [-0.72],
       [-0.7 ],
       [-0.68],
       [-0.66],
       [-0.64],
       [-0.62],
       [-0.6 ],
       [-0.58],
       [-0.56],
       [-0.54],
       [-0.52],
       [-0.5 ],
       [-0.48],
       [-0.46],
       [-0.44],
       [-0.42],
       [-0.4 ],
       [-0.38],
       [-0.36],
       [-0.34],
       [-0.32],
       [-0.3 ],
       [-0.28],
       [-0.26],
       [-0.24],
       [-0.22],
       [-0.2 ],
       [-0.18],
       [-0.16],
       [-0.14],
       [-0.12],
       [-0.1 ],
       [-0.08],
       [-0.06],
       [-0.04],
       [-0.02],
       [ 0.  ],
       [ 0.02],
       [ 0.04],
       [ 0.06],
       [ 0.08],
       [ 0.1 ],
       [ 0.12],
       [ 0.14],
       [ 0.16],
       [ 0.18],
       [ 0.2 ],
       [ 0.22],
       [

In [22]:
#define no of nodes in each layer..
INPUT_NODES = 1
HIDDEN_NODES = 20
OUTPUT_NODES = 1

In [23]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [88]:
def forward_pass(input_X, output_Y, W):


    if isinstance(W, Particle):
        W = W.p

    w1 = W[0 : INPUT_NODES * HIDDEN_NODES].reshape((INPUT_NODES, HIDDEN_NODES))
    b1 = W[INPUT_NODES * HIDDEN_NODES:(INPUT_NODES * HIDDEN_NODES) + HIDDEN_NODES].reshape((HIDDEN_NODES, ))
    w2 = W[(INPUT_NODES * HIDDEN_NODES) + HIDDEN_NODES:(INPUT_NODES * HIDDEN_NODES) + HIDDEN_NODES +\
        (HIDDEN_NODES * OUTPUT_NODES)].reshape((HIDDEN_NODES, OUTPUT_NODES))
    b2 = W[(INPUT_NODES * HIDDEN_NODES) + HIDDEN_NODES + (HIDDEN_NODES * OUTPUT_NODES): (INPUT_NODES *\
        HIDDEN_NODES) + HIDDEN_NODES + (HIDDEN_NODES * OUTPUT_NODES) + OUTPUT_NODES].reshape((OUTPUT_NODES, ))


    z1 = np.dot(input_X, w1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, w2) + b2
    output_from_outputlayer = sigmoid(z2)
    
    mserror = ((1/100)* (np.power((output_from_outputlayer - output_Y), 2)))
    print(mserror.sum()/100)

    return mserror
   

In [89]:
def predict(input_X, W):
  
    w1 = W[0: INPUT_NODES * HIDDEN_NODES].reshape((INPUT_NODES, HIDDEN_NODES))
    b1 = W[INPUT_NODES * HIDDEN_NODES:(INPUT_NODES * HIDDEN_NODES) + HIDDEN_NODES].reshape((HIDDEN_NODES,))
    w2 = W[(INPUT_NODES * HIDDEN_NODES) + HIDDEN_NODES:(INPUT_NODES * HIDDEN_NODES) + HIDDEN_NODES + \
        (HIDDEN_NODES * OUTPUT_NODES)].reshape((HIDDEN_NODES, OUTPUT_NODES))
    b2 = W[(INPUT_NODES * HIDDEN_NODES) + HIDDEN_NODES + (HIDDEN_NODES * OUTPUT_NODES): (INPUT_NODES * \
        HIDDEN_NODES) + HIDDEN_NODES + (HIDDEN_NODES * OUTPUT_NODES) + OUTPUT_NODES].reshape((OUTPUT_NODES,))

    z1 = np.dot(input_X, w1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, w2) + b2
    output_from_outputlayer = sigmoid(z2)
    #Y_pred = np.argmax(output_from_outputlayer, axis=1)
   
    #print(output_from_outputlayer.shape)
    Y_pred = np.argwhere(output_from_outputlayer>=0.8)
    
    return Y_pred

In [90]:
def get_accuracy(output_Y, Y_pred):
    return len(Y_pred)/len(output_Y)*100

In [91]:
if __name__ == '__main__':
    no_solution = 100
    dims = (INPUT_NODES * HIDDEN_NODES) + HIDDEN_NODES + (HIDDEN_NODES * OUTPUT_NODES) + OUTPUT_NODES
    w_range = (0.0, 1.0)
    lr_range = (0.0, 1.0)
    alpha_range = (0.9, 0.9)  
    components = (0.5, 0.3)  
    #arr = np.array(output_from_outputlayer)
    s = Swarm(no_solution, dims, w_range, lr_range, alpha_range, components)
 
    s.optimize(forward_pass, input_X, output_Y, 100, 1)
    W = s.get_best_solution()
    Y_pred = predict(input_X, W)
    accuracy = get_accuracy(output_Y, Y_pred)
    print("Accuracy: %.3f"% accuracy)


0.01345932285798051
0.01351728722907555
0.013493633744084917
0.01351379138280269
0.013525663887280062
0.013500017816018603
0.013481696271919492
0.013521902992012337
0.013506622160237132
0.013480871311921034
0.01344373757060491
0.013501896519659844
0.013516723878704284
0.013498318575466881
0.013470377815348385
0.013485926926531578
0.013517667647308058
0.013419087089133686
0.013505468083220475
0.01350831575594864
0.013445478738491959
0.013476717145567531
0.013514709436686465
0.01339139361353638
0.013440668849295994
0.013501355039144998
0.013494483537130297
0.01350086267669482
0.013487847371154375
0.013482308326654266
0.013428196454580927
0.013449588018915987
0.013399672371278282
0.013438111821355032
0.013442970366112625
0.013478276166586372
0.013525674417982832
0.013485552841190539
0.013459996331036395
0.01342857177194591
0.013503605032733422
0.013453469951621267
0.013220511963458293
0.013442810826269278
0.013477565766919535
0.013424358429923027
0.013507343629875062
0.013493371444052795
