In [534]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [281]:
class Particle:
   
    def __init__(self, dims, p_range, v_range):
        
        #dims = number of dimensions
        #p= position of the particle in the dimentional space
        #v = velocity of the particle in the dimensional space
        #p_range = range of dimensions 
        #v_range = range of velocities
        
        #let the position and velocity of a praticle be randomly selected from uniform distribution
        self.p = np.random.uniform(p_range[0], p_range[1], (dims, ))
        self.v = np.random.uniform(v_range[0], v_range[1], (dims, )) 
        
        #the best position for any particle can be positive infinity
        self.pbest = -1 #np.inf
        
        #define particles best position based on specified dimensions
        self.pbestpos = np.zeros((dims, ))

In [536]:
class Swarm:
    
    def __init__(self, particle_no, dims, p_range, v_range, alpha_range, component):
        
        #particle_no = number of particles
        #dims = dimensions
        #p_range = range of dimensions 
        #v_range = range of velocities
        #alpha_range = inertia weight range
        #components = cognetive and social components
        
        
        #define the swarm with praticles from Class Particle
        self.p = np.array([Particle(dims, p_range, v_range) for i in range(particle_no)])
        
        #define global best as infinity
        self.gbest = np.inf
        
        #define global best poition
        self.gbestpos = np.zeros((dims, ))
        
        self.p_range = p_range
        self.v_range = v_range
        
        self.alpha_range = alpha_range
        
        #components
        self.component0 = component[0]
        self.component1 = component[1]
        self.dims = dims
        
        self.mserror = []
        self.no_of_iterations = []
        self.graphic_iters = []
        self.actual_iters = range(100)
        
    def drawGraph(self):
        plt.plot(range(100), self.mserror, color='black')
       
    def optimize(self, function, input_X, output_Y,  print_step,  iter):
        informants = 6 
        for i in range(iter):
            for particle in self.p:
                fitness = function(input_X, output_Y, particle.p)

                #select the particles best position
                if fitness.any() < particle.pbest:
                    particle.pbest = fitness.any()
                    particle.pbestpos = particle.p.copy()
                    
            for i in range(informants):
                for particle in self.p:          
                
                #select the global best position    
                 if fitness.any()< self.gbest:
                    self.gbest = fitness.any()
                    self.gbestpos = particle.p.copy()
                    

            for particle in self.p:
               
                alpha = np.random.uniform(self.alpha_range[0], self.alpha_range[1], 1)[0]
                
                #velocity update formula
                particle.v = alpha * particle.v + (self.component0 * np.random.uniform(0.0, 1.0, (self.dims, )) * \
                (particle.pbestpos - particle.p)) + (self.component1 * np.random.uniform(0.0, 1.0, (self.dims, )) \
                * (self.gbestpos - particle.p))
                epsilon = 0.2
                #particle.v = particle.v.clip(min=self.v_range[0], max=self.v_range[1])
                particle.p = particle.p + epsilon * particle.v
                #particle.x = particle.x.clip(min=self.x_range[0], max=self.x_range[1])
                    
            #if i % print_step == 0:
               # print('iteration#: ', i+1,  ' loss: ', fitness)

        #print("global best loss: ", self.gbest)
        
    def get_best_solution(self):
    
        return self.gbestpos   


In [283]:
import csv
with open("X_linear.csv", 'r') as f:
    Xin = list(csv.reader(f, delimiter=";"))
import numpy as np
Xin = np.array(Xin[1:], dtype=np.float)
print(Xin)
print(Xin.shape)

[[-1.  ]
 [-0.98]
 [-0.96]
 [-0.94]
 [-0.92]
 [-0.9 ]
 [-0.88]
 [-0.86]
 [-0.84]
 [-0.82]
 [-0.8 ]
 [-0.78]
 [-0.76]
 [-0.74]
 [-0.72]
 [-0.7 ]
 [-0.68]
 [-0.66]
 [-0.64]
 [-0.62]
 [-0.6 ]
 [-0.58]
 [-0.56]
 [-0.54]
 [-0.52]
 [-0.5 ]
 [-0.48]
 [-0.46]
 [-0.44]
 [-0.42]
 [-0.4 ]
 [-0.38]
 [-0.36]
 [-0.34]
 [-0.32]
 [-0.3 ]
 [-0.28]
 [-0.26]
 [-0.24]
 [-0.22]
 [-0.2 ]
 [-0.18]
 [-0.16]
 [-0.14]
 [-0.12]
 [-0.1 ]
 [-0.08]
 [-0.06]
 [-0.04]
 [-0.02]
 [ 0.  ]
 [ 0.02]
 [ 0.04]
 [ 0.06]
 [ 0.08]
 [ 0.1 ]
 [ 0.12]
 [ 0.14]
 [ 0.16]
 [ 0.18]
 [ 0.2 ]
 [ 0.22]
 [ 0.24]
 [ 0.26]
 [ 0.28]
 [ 0.3 ]
 [ 0.32]
 [ 0.34]
 [ 0.36]
 [ 0.38]
 [ 0.4 ]
 [ 0.42]
 [ 0.44]
 [ 0.46]
 [ 0.48]
 [ 0.5 ]
 [ 0.52]
 [ 0.54]
 [ 0.56]
 [ 0.58]
 [ 0.6 ]
 [ 0.62]
 [ 0.64]
 [ 0.66]
 [ 0.68]
 [ 0.7 ]
 [ 0.72]
 [ 0.74]
 [ 0.76]
 [ 0.78]
 [ 0.8 ]
 [ 0.82]
 [ 0.84]
 [ 0.86]
 [ 0.88]
 [ 0.9 ]
 [ 0.92]
 [ 0.94]
 [ 0.96]
 [ 0.98]]
(100, 1)


In [284]:
#input_X = layer1_input.values
input_X= Xin
input_X

array([[-1.  ],
       [-0.98],
       [-0.96],
       [-0.94],
       [-0.92],
       [-0.9 ],
       [-0.88],
       [-0.86],
       [-0.84],
       [-0.82],
       [-0.8 ],
       [-0.78],
       [-0.76],
       [-0.74],
       [-0.72],
       [-0.7 ],
       [-0.68],
       [-0.66],
       [-0.64],
       [-0.62],
       [-0.6 ],
       [-0.58],
       [-0.56],
       [-0.54],
       [-0.52],
       [-0.5 ],
       [-0.48],
       [-0.46],
       [-0.44],
       [-0.42],
       [-0.4 ],
       [-0.38],
       [-0.36],
       [-0.34],
       [-0.32],
       [-0.3 ],
       [-0.28],
       [-0.26],
       [-0.24],
       [-0.22],
       [-0.2 ],
       [-0.18],
       [-0.16],
       [-0.14],
       [-0.12],
       [-0.1 ],
       [-0.08],
       [-0.06],
       [-0.04],
       [-0.02],
       [ 0.  ],
       [ 0.02],
       [ 0.04],
       [ 0.06],
       [ 0.08],
       [ 0.1 ],
       [ 0.12],
       [ 0.14],
       [ 0.16],
       [ 0.18],
       [ 0.2 ],
       [ 0.22],
       [

In [285]:
print(input_X.shape)

(100, 1)


In [286]:
output_Y = np.zeros(shape=(100,1))

In [287]:
perfect_predict_Y = np.full((100, 1), 1, dtype=int)

In [288]:
print(perfect_predict_Y.shape)
perfect_predict_Y 

(100, 1)


array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [289]:
def linear(input_X):
    output_Y = input_X * 1
    return output_Y

In [290]:
output_Y = linear(input_X)

In [291]:
output_Y

array([[-1.  ],
       [-0.98],
       [-0.96],
       [-0.94],
       [-0.92],
       [-0.9 ],
       [-0.88],
       [-0.86],
       [-0.84],
       [-0.82],
       [-0.8 ],
       [-0.78],
       [-0.76],
       [-0.74],
       [-0.72],
       [-0.7 ],
       [-0.68],
       [-0.66],
       [-0.64],
       [-0.62],
       [-0.6 ],
       [-0.58],
       [-0.56],
       [-0.54],
       [-0.52],
       [-0.5 ],
       [-0.48],
       [-0.46],
       [-0.44],
       [-0.42],
       [-0.4 ],
       [-0.38],
       [-0.36],
       [-0.34],
       [-0.32],
       [-0.3 ],
       [-0.28],
       [-0.26],
       [-0.24],
       [-0.22],
       [-0.2 ],
       [-0.18],
       [-0.16],
       [-0.14],
       [-0.12],
       [-0.1 ],
       [-0.08],
       [-0.06],
       [-0.04],
       [-0.02],
       [ 0.  ],
       [ 0.02],
       [ 0.04],
       [ 0.06],
       [ 0.08],
       [ 0.1 ],
       [ 0.12],
       [ 0.14],
       [ 0.16],
       [ 0.18],
       [ 0.2 ],
       [ 0.22],
       [

In [457]:
#ANN architecture
#define no of nodes in each layer..
Input = 1
Hidden = 200
Output = 1

In [350]:
sig_Y = sigmoid(sigmoid(input_X))

In [293]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [489]:
df = pd.DataFrame(columns=['MSE', 'Output_Y', 'Predicted_Y'])
print(df)

Empty DataFrame
Columns: [MSE, Output_Y, Predicted_Y]
Index: []


In [502]:
def forward_pass(input_X, output_Y, W):


    if isinstance(W, Particle):
        W = W.p

    w1 = W[0 : Input * Hidden].reshape((Input, Hidden))

    b1 = W[Input * Hidden:(Input * Hidden) + Hidden].reshape((Hidden, ))
    w2 = W[(Input * Hidden) + Hidden:(Input * Hidden) + Hidden +\
        (Hidden * Output)].reshape((Hidden, Output))
    
    b2 = W[(Input * Hidden) + Hidden + (Hidden * Output): (Input *\
        Hidden) + Hidden + (Hidden * Output) + Output].reshape((Output, ))


    z1 = np.dot(input_X, w1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, w2) + b2
    output_from_outputlayer = sigmoid(z2)
    
       
    mserror1 = (np.power((output_from_outputlayer - output_Y), 2))
    mserror = (mserror1.sum()/100)
    print(mserror)
    
    
    
    return mserror
   

In [524]:
def pass_information(input_X, W):


    if isinstance(W, Particle):
        W = W.p

    w1 = W[0 : Input * Hidden].reshape((Input, Hidden))

    b1 = W[Input * Hidden:(Input * Hidden) + Hidden].reshape((Hidden, ))
    w2 = W[(Input * Hidden) + Hidden:(Input * Hidden) + Hidden +\
        (Hidden * Output)].reshape((Hidden, Output))
    
    b2 = W[(Input * Hidden) + Hidden + (Hidden * Output): (Input *\
        Hidden) + Hidden + (Hidden * Output) + Output].reshape((Output, ))


    z1 = np.dot(input_X, w1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, w2) + b2
    output_from_outputlayer = sigmoid(z2)
    
       
    mserror1 = (np.power((output_from_outputlayer - output_Y), 2))
    mserror = (mserror1.sum()/100)
   
    df = pd.DataFrame(columns=['MSE'])
    #df2 = pd.DataFrame(columns=cols, index=range(2))
    
    df = df.append({'MSE': mserror}, ignore_index=True)
        
    
    
    #df = pd.DataFrame(columns=['MSE'])

    #df = df.append({'MSE': mserror}, ignore_index=True)
    #print(df)
    
    return df
   

In [440]:
def predict(input_X, W):
  
    w1 = W[0 : Input * Hidden].reshape((Input, Hidden))

    b1 = W[Input * Hidden:(Input * Hidden) + Hidden].reshape((Hidden, ))
    w2 = W[(Input * Hidden) + Hidden:(Input * Hidden) + Hidden +\
        (Hidden * Output)].reshape((Hidden, Output))
    
    b2 = W[(Input * Hidden) + Hidden + (Hidden * Output): (Input *\
        Hidden) + Hidden + (Hidden * Output) + Output].reshape((Output, ))

    z1 = np.dot(input_X, w1) + b1
    a1 = sigmoid(z1)
    z2 = np.dot(a1, w2) + b2
    output_from_outputlayer = sigmoid(z2)
    
    comparison = np.round(sig_Y, 2) == np.round(output_from_outputlayer, 2)
   # np.sum(np.round(sig_Y, 2) == np.round(output_from_outputlayer, 2))
    #print((np.round(sig_Y, 2)  == np.round(output_from_outputlayer, 2)).sum())
    #print(comparison.sum())
    
    
    #Y_pred = np.argmax(output_from_outputlayer, axis=1)
   
    #print(output_from_outputlayer.shape)
    Y_pred = comparison.sum()
    return Y_pred

In [441]:
def get_accuracy(output_Y, Y_pred):
    return (Y_pred)*100/100

In [539]:
if __name__ == '__main__':
    no_solution = 1
 
    dims = (Input * Hidden) + Hidden + (Hidden * Output) + Output
    w_range = (-1, 1)
    lr_range = (0.0, 0.5)
    alpha_range = (0.8, 0.9)  
    components = (3, 1)  
    #arr = np.array(output_from_outputlayer)
    s = Swarm(no_solution, dims, w_range, lr_range, alpha_range, components)
    
    iterations = 2
    s.optimize(forward_pass, input_X, output_Y, 200,iterations)
    
    W = s.get_best_solution()
    Y_pred = predict(input_X, W)
    accuracy = get_accuracy(output_Y, Y_pred)
    Average_accuracy = accuracy.sum()/iterations
    #s.drawGraph()
    
    for i in range(iterations):
        pass_info = pass_information(input_X, W)
        print(pass_info)
    
    
    
    #df2 = pd.DataFrame(columns=['Accuracy', 'Average Solution Accuracy'])
    #df2 = df2.append({'Accuracy': accuracy, 'Average Solution Accuracy': Average_accuracy}, ignore_index=True)
   # print(df2)
    
    #print("Accuracy: %.3f"% Average_accuracy)


0.33310291363040995
0.9825272878580562
        MSE
0  0.333103
        MSE
0  0.333103
